version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - gocognit
    - goconst
    - gomodguard
    - lll
    - nlreturn
    - noinlineerr
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - testpackage
    - gochecknoglobals
    - mnd
    - godox
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
  exclusions:
    rules:
      - path: "keymap.go"
        linters:
          - godoclint
formatters:
  enable:
    - gofumpt
    - goimports
